//
//  BonjourDiscoveryTypes.swift
//  SideStore
//
//  Created by Magesh K on 4/7/26.
//  Copyright © 2026 SideStore. All rights reserved.
//

import Foundation

public let commonServiceTypesToBrowse: [String] = [
    "_altserver._tcp.",
    "_remotepairing-pairable-host._tcp.",
    "_airplay._tcp.",
    "_raop._tcp.",
    "_sftp-ssh._tcp.",
    "_sleep-proxy._udp.",
    "_ssh._tcp.",
    "_apple-mobdev2._tcp.",
    "_asquic._udp.",
    "_companion-link._tcp.",
    "_meshcop._udp.",
    "_remotepairing._tcp.",
    "_rp-tunnel._tcp.",
    "_srpl-tls._tcp.",
    "_trel._udp.",
    "_http._tcp.",
    "_https._tcp.",
    "_smb._tcp.",
    "_afpovertcp._tcp.",
    "_printer._tcp.",
    "_ipp._tcp.",
    "_ipps._tcp.",
    "_scanner._tcp.",
    "_daap._tcp.",
    "_dpap._tcp.",
    "_airport._tcp.",
    "_homekit._tcp.",
    "_hap._tcp.",
    "_touch-able._tcp.",
    "_spotify-connect._tcp.",
    "_googlecast._tcp.",
    "_device-info._tcp.",
    "_workstation._tcp.",
    "_rfb._tcp.",
    "_net-assistant._udp.",
    "_rdlink._tcp.",
    "_stikpairprobe._tcp.",
    "_webdav._tcp.",
    "_webdavs._tcp.",
    "_ftp._tcp.",
    "_telnet._tcp.",
    "_coap._udp.",
    "_coaps._udp.",
    "_mqtt._tcp.",
    "_adb._tcp.",
    "_airdrop._tcp.",
    "_sidecar._tcp.",
    "_sonos._tcp.",
    "_plex._tcp.",
    "_amzn-alexa._tcp.",
    "_home-assistant._tcp.",
    "_rtsp._tcp.",
    "_sip._udp.",
    "_sip._tcp.",
    "_h323._tcp.",
    "_h323._udp.",
    "_ws._tcp.",
    "_wss._tcp."
]

public let commonKnownServiceTypes: [String: String] = [
    "_airplay._tcp.":       "音视频内容流媒体传输协议",
    "_raop._tcp.":          "远程音频输出协议（AirTunes）",
    "_sftp-ssh._tcp.":      "基于 SSH 的安全文件传输协议",
    "_sleep-proxy._udp.":   "睡眠代理服务器",
    "_ssh._tcp.":           "SSH 远程登录协议",
    "_http._tcp.":          "万维网（HTTP）",
    "_https._tcp.":         "万维网（HTTPS）",
    "_smb._tcp.":           "SMB 文件共享",
    "_afpovertcp._tcp.":    "Apple 文件协议（AFP）",
    "_printer._tcp.":       "打印机",
    "_ipp._tcp.":           "互联网打印协议",
    "_scanner._tcp.":       "扫描仪",
    "_ftp._tcp.":           "文件传输协议",
    "_nfs._tcp.":           "网络文件系统",
    "_daap._tcp.":          "数字音频访问协议（iTunes）",
    "_dpap._tcp.":          "数字照片访问协议（iPhoto）",
    "_airport._tcp.":       "AirPort 基站",
    "_homekit._tcp.":       "HomeKit 配件",
    "_hap._tcp.":           "HomeKit 配件协议",
    "_companion-link._tcp.": "伴侣链接（Apple Watch）",
    "_apple-mobdev2._tcp.":  "Apple 移动设备 v2",
    "_remotepairing._tcp.":  "远程配对",
    "_remotepairing-pairable-host._tcp.": "远程配对（可配对主机）",
    "_rdlink._tcp.":        "远程调试链接",
    "_net-assistant._udp.": "Apple 远程桌面",
    "_rfb._tcp.":           "远程帧缓冲（VNC）",
    "_spotify-connect._tcp.": "Spotify Connect",
    "_googlecast._tcp.":    "Google Cast（Chromecast）",
    "_meshcop._udp.":       "Thread 网状网络配置",
    "_asquic._udp.":        "Apple QUIC 服务",
    "_rp-tunnel._tcp.":     "远程配对隧道",
    "_altserver._tcp.":     "AltServer",
    "_workstation._tcp.":   "工作站",
    "_device-info._tcp.":   "设备信息",
    "_touch-able._tcp.":    "远程应用（Apple TV 遥控器）",
    "_srpl-tls._tcp.":      "空间远程播放链接 TLS",
    "_trel._udp.":          "Thread 无线电封装链接",
    "_ipps._tcp.":          "安全互联网打印协议",
    "_webdav._tcp.":        "Web 分布式创作和版本管理（WebDAV）",
    "_webdavs._tcp.":       "安全 WebDAV",
    "_telnet._tcp.":        "Telnet 远程登录协议",
    "_coap._udp.":          "受限应用协议（CoAP）",
    "_coaps._udp.":         "安全 CoAP",
    "_mqtt._tcp.":          "消息队列遥测传输（MQTT）",
    "_adb._tcp.":           "Android 调试桥（ADB）",
    "_airdrop._tcp.":       "Apple 隔空投送",
    "_sidecar._tcp.":       "Apple 随航",
    "_sonos._tcp.":         "Sonos 音箱系统",
    "_plex._tcp.":          "Plex 媒体服务器",
    "_amzn-alexa._tcp.":    "Amazon Alexa 服务",
    "_home-assistant._tcp.": "Home Assistant 智能家居",
    "_rtsp._tcp.":          "实时流媒体协议（RTSP）",
    "_sip._udp.":           "会话发起协议（基于 UDP 的 SIP）",
    "_sip._tcp.":           "会话发起协议（基于 TCP 的 SIP）",
    "_h323._tcp.":          "H.323 视频会议（TCP）",
    "_h323._udp.":          "H.323 视频会议（UDP）",
    "_ws._tcp.":            "WebSocket 连接",
    "_wss._tcp.":           "安全 WebSocket 连接",
]
